steps:
  # Step 1: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/backend-repo/flask-backend:$COMMIT_SHA",
        "."
      ]
    dir: "flask-app"

  # Step 2: Push Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/backend-repo/flask-backend:$COMMIT_SHA"
      ]

  # Step 3: Update metadata on Compute Engine VM
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "compute",
        "instances",
        "add-metadata",
        "backend-ubuntu",
        "--zone",
        "us-central1-a",
        "--metadata",
        "gce-container-declaration=\
spec:\n\
  containers:\n\
    - name: flask-backend\n\
      image: us-central1-docker.pkg.dev/$PROJECT_ID/backend-repo/flask-backend:$COMMIT_SHA\n\
      env:\n\
        - name: PORT\n\
          value: \"5000\"\n\
restartPolicy: Always"
      ]

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/backend-repo/flask-backend:$COMMIT_SHA"
